# Generated by Django 6.0 on 2026-05-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='email',
            field=models.EmailField(max_length=10, null=True),
        ),
    ]
